- name: Install PostgreSQL dependencies
  action: apt pkg={{ item }} state=latest
  with_items:
    - python-pycurl
    - python-psycopg2
  tags: pg_install

- name: Add PostgreSQL repo key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc
  tags: pg_repo

- name: Add PostgreSQL repo
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ stretch-pgdg main'
  tags: pg_repo

- name: Install PostgreSQL
  apt: pkg=postgresql-{{ pg_version }} state=latest update_cache=true
  tags: pg_install

- name: Copy valid pg_hba.conf
  template: src=pg_hba.conf dest=/etc/postgresql/{{ pg_version }}/main/pg_hba.conf
  tags: pg_install

- name: Copy valid postgresql.conf
  template: src=postgresql.conf dest=/etc/postgresql/{{ pg_version }}/main/postgresql.conf
  tags: pg_install

- name: Autostart Postgres service
  systemd: name=postgresql.service enabled=yes
  tags: pg_install

- name: Restart PostgreSQL
  service: name=postgresql state=restarted enabled=yes
  tags: pg_restart
